//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sherlock.Executor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sherlock.Executor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {TYPE} of the channel over which the connection should be made..
        /// </summary>
        internal static string CommandLine_Param_ChannelType_Description {
            get {
                return ResourceManager.GetString("CommandLine_Param_ChannelType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t=|channeltype=.
        /// </summary>
        internal static string CommandLine_Param_ChannelType_Key {
            get {
                return ResourceManager.GetString("CommandLine_Param_ChannelType_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {URI} of the connection that can be used to connect to the host application..
        /// </summary>
        internal static string CommandLine_Param_ChannelUri_Description {
            get {
                return ResourceManager.GetString("CommandLine_Param_ChannelUri_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u=|channeluri=.
        /// </summary>
        internal static string CommandLine_Param_ChannelUri_Key {
            get {
                return ResourceManager.GetString("CommandLine_Param_ChannelUri_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {ENDPOINTID} of the host application that requested the start of this application..
        /// </summary>
        internal static string CommandLine_Param_Host_Description {
            get {
                return ResourceManager.GetString("CommandLine_Param_Host_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h=|host=.
        /// </summary>
        internal static string CommandLine_Param_Host_Key {
            get {
                return ResourceManager.GetString("CommandLine_Param_Host_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given test step is invalid for the current processor..
        /// </summary>
        internal static string Exceptions_Messages_InvalidTestStep {
            get {
                return ResourceManager.GetString("Exceptions_Messages_InvalidTestStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up for step {0} of type {1}.
        /// </summary>
        internal static string Log_Messages_CleaningUpTestStep_WithStepAndTestStepType {
            get {
                return ResourceManager.GetString("Log_Messages_CleaningUpTestStep_WithStepAndTestStepType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to host {0} with channel of type {1} at {2}.
        /// </summary>
        internal static string Log_Messages_ConnectingToHost_WithConnectionParameters {
            get {
                return ResourceManager.GetString("Log_Messages_ConnectingToHost_WithConnectionParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating storage directory at: {0}.
        /// </summary>
        internal static string Log_Messages_CreatingStorageDirectory_WithDirectory {
            get {
                return ResourceManager.GetString("Log_Messages_CreatingStorageDirectory_WithDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading test data from {0}.
        /// </summary>
        internal static string Log_Messages_DownloadingTestDataFromHost_WithHostUrl {
            get {
                return ResourceManager.GetString("Log_Messages_DownloadingTestDataFromHost_WithHostUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing test step of type: {0}.
        /// </summary>
        internal static string Log_Messages_ExecutingTestStep_WithTestStepType {
            get {
                return ResourceManager.GetString("Log_Messages_ExecutingTestStep_WithTestStepType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while cleaning up steps. Error was: {0}.
        /// </summary>
        internal static string Log_Messages_FailedToCleanUp_WithError {
            get {
                return ResourceManager.GetString("Log_Messages_FailedToCleanUp_WithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create storage directory at: {0}. Error is: {1}.
        /// </summary>
        internal static string Log_Messages_FailedToCreateStorageDirectory_WithDirectoryAndError {
            get {
                return ResourceManager.GetString("Log_Messages_FailedToCreateStorageDirectory_WithDirectoryAndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while executing steps. Error was: {0}.
        /// </summary>
        internal static string Log_Messages_FailureWhileExecutingTest_WithError {
            get {
                return ResourceManager.GetString("Log_Messages_FailureWhileExecutingTest_WithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage directory at {0} already exists. Deleting ....
        /// </summary>
        internal static string Log_Messages_RemovingStorageDirectory_WithDirectory {
            get {
                return ResourceManager.GetString("Log_Messages_RemovingStorageDirectory_WithDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test result is: {0}.
        /// </summary>
        internal static string Log_Messages_TestCompleted_WithResult {
            get {
                return ResourceManager.GetString("Log_Messages_TestCompleted_WithResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test information transferred successfully.
        /// </summary>
        internal static string Log_Messages_TestDataTransferredSuccessfully {
            get {
                return ResourceManager.GetString("Log_Messages_TestDataTransferredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a suitable processor for a test step of type: {0}.
        /// </summary>
        internal static string Log_Messages_UnableToFindSuitableTestStepProcessor_WithTestStepType {
            get {
                return ResourceManager.GetString("Log_Messages_UnableToFindSuitableTestStepProcessor_WithTestStepType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking test package from {0} to {1}.
        /// </summary>
        internal static string Log_Messages_UnpackingTestData_WithSourceAndDestination {
            get {
                return ResourceManager.GetString("Log_Messages_UnpackingTestData_WithSourceAndDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for host to connect....
        /// </summary>
        internal static string Log_Messages_WaitingForHostToConnect {
            get {
                return ResourceManager.GetString("Log_Messages_WaitingForHostToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test clean-up failed. Error was: {0}.
        /// </summary>
        internal static string Reporting_TestExecution_CleanupFailed_WithException {
            get {
                return ResourceManager.GetString("Reporting_TestExecution_CleanupFailed_WithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find suitable test step executor for test of type: {0}.
        /// </summary>
        internal static string Reporting_TestExecution_CouldNotFindSuitableExecutor_WithTestStepType {
            get {
                return ResourceManager.GetString("Reporting_TestExecution_CouldNotFindSuitableExecutor_WithTestStepType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test failed. Clean-up may not have been completed. Error was: {0}.
        /// </summary>
        internal static string Reporting_TestExecution_Failed_WithException {
            get {
                return ResourceManager.GetString("Reporting_TestExecution_Failed_WithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test execution.
        /// </summary>
        internal static string ReportSection_Group_Name_TestExecution {
            get {
                return ResourceManager.GetString("ReportSection_Group_Name_TestExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing tests.
        /// </summary>
        internal static string ReportSection_Name_TestExecution {
            get {
                return ResourceManager.GetString("ReportSection_Name_TestExecution", resourceCulture);
            }
        }
    }
}
