-------------------------------------------------------------------------------
-- <copyright company="Sherlock">
--     Copyright 2013 Sherlock. Licensed under the Apache License, Version 2.0.
-- </copyright>
-------------------------------------------------------------------------------

CREATE PROCEDURE [Tests].[AddApplicationToTestEnvironment]
    @testEnvironmentId INT,
    @applicationId INT
AS
    IF NOT EXISTS (
        SELECT * 
        FROM [Tests].[TestEnvironment]
        WHERE [pk_TestEnvironmentId] = @testEnvironmentId)
    BEGIN
        RAISERROR 
            (
                N'An entry for a test environment with ID %s does not exist.', 
                11, 
                1,
                @testEnvironmentId
            )
        RETURN
    END

    IF NOT EXISTS (
        SELECT * 
        FROM [Environments].[Application]
        WHERE [pk_ApplicationId] = @applicationId)
    BEGIN
        RAISERROR 
            (
                N'An entry for an application with ID %d does not exist.', 
                11, 
                1,
                @applicationId
            )
        RETURN
    END

    BEGIN TRANSACTION

        INSERT INTO [Tests].[TestApplication]
            (
                [fk_TestEnvironmentId],
                [fk_ApplicationId]
            )
        VALUES
            (
                @testEnvironmentId,
                @applicationId
            )

        --Return the autogenerated value for mapping back into the entity
        DECLARE @id INT

        SELECT @id = [pk_TestApplicationId]
        FROM [Tests].[TestApplication]
        WHERE [pk_TestApplicationId] = SCOPE_IDENTITY()

        IF @@ERROR <> 0
        BEGIN
            ROLLBACK

            RAISERROR 
                (
                    'Failed to insert application with ID %s.', 
                    11, 
                    1,
                    @id
                )
            RETURN
        END

    COMMIT
    SELECT @id as Id