-------------------------------------------------------------------------------
-- <copyright company="Sherlock">
--     Copyright 2013 Sherlock. Licensed under the Apache License, Version 2.0.
-- </copyright>
-------------------------------------------------------------------------------

CREATE PROCEDURE [Environments].[AddApplication]
    @name NVARCHAR(50),
    @major INT,
    @minor INT,
    @patch INT,
    @build INT
AS
    IF EXISTS(
        SELECT *
        FROM [Environments].[Application]
        WHERE
            [Name] = @name AND
            [VersionMajor] = @major AND
            [VersionMinor] = @minor AND
            [VersionPatch] = @patch AND
            [VersionBuild] = @build)
    BEGIN
        RAISERROR 
            (
                N'An entry for an application %s (%d.%d.%d.%d) already exists', 
                11, 
                1,
                @name,
                @major,
                @minor,
                @patch,
                @build
            )
        RETURN
    END

    BEGIN TRANSACTION

        INSERT INTO [Environments].[Application]
            (
                [Name],
                [VersionMajor],
                [VersionMinor],
                [VersionPatch],
                [VersionBuild]
            )
        VALUES
            (
                @name,
                @major,
                @minor,
                @patch,
                @build
            )

        --Return the autogenerated value for mapping back into the entity
        DECLARE @id INT

        SELECT @id = [pk_ApplicationId]
        FROM [Environments].[Application]
        WHERE [pk_ApplicationId] = SCOPE_IDENTITY()

        IF @@ERROR <> 0
        BEGIN
            ROLLBACK

            RAISERROR 
                (
                    'Failed to insert application with ID %s.', 
                    11, 
                    1,
                    @id
                )
            RETURN
        END

    COMMIT
    SELECT @id as Id
