-------------------------------------------------------------------------------
-- <copyright company="Sherlock">
--     Copyright 2013 Sherlock. Licensed under the Apache License, Version 2.0.
-- </copyright>
-------------------------------------------------------------------------------

CREATE PROCEDURE [Environments].[AddApplicationToMachine]
    @machineId NVARCHAR(50),
    @applicationId INT
AS
    IF NOT EXISTS (
        SELECT * 
        FROM [Environments].[Machine]
        WHERE [pk_MachineId] = @machineId)
    BEGIN
        RAISERROR 
            (
                N'An entry for a machine with ID %s does not exist.', 
                11, 
                1,
                @machineId
            )
        RETURN
    END

    IF NOT EXISTS (
        SELECT * 
        FROM [Environments].[Application]
        WHERE [pk_ApplicationId] = @applicationId)
    BEGIN
        RAISERROR 
            (
                N'An entry for an application with ID %d does not exist.', 
                11, 
                1,
                @applicationId
            )
        RETURN
    END

    BEGIN TRANSACTION

        INSERT INTO [Environments].[MachineApplication]
            (
                [fk_MachineId],
                [fk_ApplicationId]
            )
        VALUES
            (
                @machineId,
                @applicationId
            )

        --Return the autogenerated value for mapping back into the entity
        DECLARE @id INT

        SELECT @id = [pk_MachineApplicationId]
        FROM [Environments].[MachineApplication]
        WHERE [pk_MachineApplicationId] = SCOPE_IDENTITY()

        IF @@ERROR <> 0
        BEGIN
            ROLLBACK

            RAISERROR 
                (
                    'Failed to insert application with ID %s.', 
                    11, 
                    1,
                    @id
                )
            RETURN
        END

    COMMIT
    SELECT @id as Id