-------------------------------------------------------------------------------
-- <copyright company="Sherlock">
--     Copyright 2013 Sherlock. Licensed under the Apache License, Version 2.0.
-- </copyright>
-------------------------------------------------------------------------------

CREATE PROCEDURE [Environments].[AddOperatingSystem]
    @name NVARCHAR(50),
    @servicePack NVARCHAR(50),
    @architecturePointerSize INT,
    @culture NVARCHAR(50)
AS
    IF EXISTS (
        SELECT * 
        FROM [Environments].[OperatingSystem] 
        WHERE 
            [Name] = @name AND 
            [ServicePack] = @servicePack AND
            [ArchitecturePointerSize] = @architecturePointerSize AND
            [Culture] = @culture)
    BEGIN
        RAISERROR 
            (
                N'An entry for an operating system %s (%s) - %d - %s already exists', 
                11, 
                1,
                @name,
                @servicePack,
                @architecturePointerSize,
                @culture
            )
        RETURN
    END

    BEGIN TRANSACTION

        INSERT INTO [Environments].[OperatingSystem]
            (
                [Name],
                [ServicePack],
                [ArchitecturePointerSize],
                [Culture]
            )
        VALUES
            (
                @name,
                @servicePack,
                @architecturePointerSize,
                @culture
            )

        --Return the autogenerated value for mapping back into the entity
        DECLARE @id INT

        SELECT @id = [pk_OperatingSystemId]
        FROM [Environments].[OperatingSystem]
        WHERE [pk_OperatingSystemId] = SCOPE_IDENTITY()

        IF @@ERROR <> 0
        BEGIN
            ROLLBACK

            RAISERROR 
                (
                    'Failed to insert operating system with ID %s.', 
                    11, 
                    1,
                    @id
                )
            RETURN
        END

    COMMIT
    SELECT @id as Id