//-----------------------------------------------------------------------
// <copyright company="Sherlock">
//     Copyright 2013 Sherlock. Licensed under the Apache License, Version 2.0.
// </copyright>
//-----------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sherlock.Shared.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Stores information about a Hyper-V machine available for testing.
    /// </summary>
    public partial class HypervMachineDescription : MachineDescription
    {
        /// <summary>
        /// Gets or sets the name of the virtual machine image.
        /// </summary>
        public string Image { get; set; }
    
        /// <summary>
        /// Gets or sets the name of the snapshot to which the virtual machine should be returned after use.
        /// </summary>
        public string SnapshotToReturnTo { get; set; }
    
        /// <summary>
        /// Gets the ID of the machine that hosts the image for the current Hyper-V virtual machine.
        /// </summary>
        internal string fk_HostId { get; set; }
    
        /// <summary>
        /// Gets or sets the machine that hosts the image for the current virtual machine.
        /// </summary>
        public MachineDescription HostMachine { get; set; }
    
    }
}
