//-----------------------------------------------------------------------
// <copyright company="Sherlock">
//     Copyright 2013 Sherlock. Licensed under the Apache License, Version 2.0.
// </copyright>
//-----------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sherlock.Shared.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Stores information about an application that is installed on a specific machine.
    /// </summary>
    public partial class MachineApplication
    {
        /// <summary>
        /// Gets the ID of the application install.
        /// </summary>
        internal int pk_MachineApplicationId { get; set; }
    
        /// <summary>
        /// Gets the ID of the machine on which the application is installed.
        /// </summary>
        internal string fk_MachineId { get; set; }
    
        /// <summary>
        /// Gets the ID of the installed application.
        /// </summary>
        internal int fk_ApplicationId { get; set; }
    
        /// <summary>
        /// Gets the application.
        /// </summary>
        public ApplicationDescription Application { get; internal set; }
    
        /// <summary>
        /// Gets the machine.
        /// </summary>
        public MachineDescription Machine { get; internal set; }
    
    }
}
