//-----------------------------------------------------------------------
// <copyright company="Sherlock">
//     Copyright 2013 Sherlock. Licensed under the Apache License, Version 2.0.
// </copyright>
//-----------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sherlock.Shared.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Defines an environment required for a given test.
    /// </summary>
    public partial class TestEnvironment
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TestEnvironment" /> class.
        /// </summary>
        public TestEnvironment()
        {
            this.TestApplications = new HashSet<TestApplication>();
            this.TestSteps = new HashSet<TestStep>();
        }
    
        /// <summary>
        /// Gets or sets the ID of the test environment.
        /// </summary>
        internal int pk_TestEnvironmentId { get; set; }
    
        /// <summary>
        /// Gets or sets the ID of the test related to the current test environment.
        /// </summary>
        internal int fk_TestId { get; set; }
    
        /// <summary>
        /// Gets or sets the ID of the operating system desired for the environment.
        /// </summary>
        internal int fk_DesiredOperatingSystemId { get; set; }
    
        /// <summary>
        /// Gets or sets the name of the environment.
        /// </summary>
        internal string EnvironmentName { get; set; }
    
        /// <summary>
        /// Gets or sets the ID of the machine selected for the environment.
        /// </summary>
        internal string fk_SelectedMachineId { get; set; }
    
        /// <summary>
        /// Gets or sets the machine that will be used to satisfy the environment demand.
        /// </summary>
        public MachineDescription Machine { get; internal set; }
    
        /// <summary>
        /// Gets or sets the operating system required for the environment.
        /// </summary>
        public OperatingSystemDescription OperatingSystem { get; internal set; }
    
        /// <summary>
        /// Gets or sets the test to which the environment belongs.
        /// </summary>
        internal Test Test { get; set; }
    
        /// <summary>
        /// Gets or sets the collection of application required for the environment.
        /// </summary>
        internal ICollection<TestApplication> TestApplications { get; set; }
    
        /// <summary>
        /// Gets or sets the collection containing the test steps for the current environment.
        /// </summary>
        internal ICollection<TestStep> TestSteps { get; set; }
    
    }
}
