//-----------------------------------------------------------------------
// <copyright company="Sherlock">
//     Copyright 2013 Sherlock. Licensed under the Apache License, Version 2.0.
// </copyright>
//-----------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sherlock.Shared.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Defines a test that should be executed.
    /// </summary>
    public partial class Test
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Test" /> class.
        /// </summary>
        public Test()
        {
            this.TestEnvironments = new HashSet<TestEnvironment>();
        }
    
        /// <summary>
        /// Gets or sets the ID of the test.
        /// </summary>
        internal int pk_TestId { get; set; }
    
        /// <summary>
        /// Gets or sets the name of the product that is being tested.
        /// </summary>
        public string ProductName { get; set; }
    
        /// <summary>
        /// Gets or sets the version of the product that is being tested.
        /// </summary>
        public string ProductVersion { get; set; }
    
        /// <summary>
        /// Gets or sets the name of the user that requested the test.
        /// </summary>
        public string Owner { get; set; }
    
        /// <summary>
        /// Gets or sets the description for the current test.
        /// </summary>
        public string TestDescription { get; set; }
    
        /// <summary>
        /// Gets or sets the date and time on which the test was requested.
        /// </summary>
        public System.DateTimeOffset RequestTime { get; internal set; }
    
        /// <summary>
        /// Gets or sets the date and time on which the test was started.
        /// </summary>
        public Nullable<System.DateTimeOffset> StartTime { get; internal set; }
    
        /// <summary>
        /// Gets or sets the date and time on which the test was completed.
        /// </summary>
        public Nullable<System.DateTimeOffset> EndTime { get; internal set; }
    
        /// <summary>
        /// Gets or sets the full path to the directory in which the test report should be placed.
        /// </summary>
        public string ReportPath { get; set; }
    
        /// <summary>
        /// Gets or sets a value indicating whether the test setup is completed and the test is ready for execution.
        /// </summary>
        internal bool IsReadyForExecution { get; set; }
    
        /// <summary>
        /// Gets or sets the collection containing all the environments required for the test.
        /// </summary>
        internal ICollection<TestEnvironment> TestEnvironments { get; set; }
    
    }
}
