//-----------------------------------------------------------------------
// <copyright company="Sherlock">
//     Copyright 2013 Sherlock. Licensed under the Apache License, Version 2.0.
// </copyright>
//-----------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sherlock.Shared.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Stores parameter information for a given test step.
    /// </summary>
    public partial class TestStepParameter
    {
        /// <summary>
        /// Gets or sets the ID of the parameter
        /// </summary>
        internal int pk_TestStepParameterId { get; set; }
    
        /// <summary>
        /// Gets or sets the ID of the test step associated with the current parameter.
        /// </summary>
        internal int fk_TestStepId { get; set; }
    
        /// <summary>
        /// Gets or sets the key.
        /// </summary>
        public string Key { get; set; }
    
        /// <summary>
        /// Gets or sets the value.
        /// </summary>
        public string Value { get; set; }
    
        /// <summary>
        /// Gets or sets the test step associated with the current parameter.
        /// </summary>
        internal TestStep TestStep { get; set; }
    
    }
}
