//-----------------------------------------------------------------------
// <copyright company="Sherlock">
//     Copyright 2013 Sherlock. Licensed under the Apache License, Version 2.0.
// </copyright>
//-----------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sherlock.Shared.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Maps an application to a test environment.
    /// </summary>
    public partial class TestApplication
    {
        /// <summary>
        /// Gets or sets the ID of the application mapping.
        /// </summary>
        internal int pk_TestApplicationId { get; set; }
    
        /// <summary>
        /// Gets or sets the ID of the test environment.
        /// </summary>
        internal int fk_TestEnvironmentId { get; set; }
    
        /// <summary>
        /// Gets or sets the ID of the application.
        /// </summary>
        internal int fk_ApplicationId { get; set; }
    
        /// <summary>
        /// Gets or sets the application.
        /// </summary>
        public ApplicationDescription Application { get; internal set; }
    
        /// <summary>
        /// Gets or sets the environment.
        /// </summary>
        public TestEnvironment TestEnvironment { get; internal set; }
    
    }
}
