//-----------------------------------------------------------------------
// <copyright company="Sherlock">
//     Copyright 2013 Sherlock. Licensed under the Apache License, Version 2.0.
// </copyright>
//-----------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sherlock.Shared.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Stores the directories for each test step that should be included in the final report.
    /// </summary>
    public partial class TestStepReportDirectory
    {
        /// <summary>
        /// Gets or sets the ID of the report directory.
        /// </summary>
        internal int pk_TestStepReportDirectoryId { get; set; }
    
        /// <summary>
        /// Gets or sets the ID of the test step associated with the current report directory.
        /// </summary>
        internal int fk_TestStepId { get; set; }
    
        /// <summary>
        /// Gets or sets the full path to the report directory.
        /// </summary>
        public string Path { get; set; }
    
        /// <summary>
        /// Gets or sets the test step associated with the current report directory.
        /// </summary>
        internal TestStep TestStep { get; set; }
    
    }
}
