//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sherlock.Shared.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sherlock.Shared.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application: {0} at version {1}.
        /// </summary>
        internal static string ApplicationSpecification_ToString {
            get {
                return ResourceManager.GetString("ApplicationSpecification_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to run {0}. Error: {1}.
        /// </summary>
        internal static string ConsoleApplicationRunner_Error_FailedToRunExe_WithPathAndError {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_Error_FailedToRunExe_WithPathAndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string ConsoleApplicationRunner_ErrorWhileRunning_WithError {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_ErrorWhileRunning_WithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process finished. Total time: {0}
        ///{1}.
        /// </summary>
        internal static string ConsoleApplicationRunner_Output_ProcessCompleted_WithTimeAndProcessStats {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_Output_ProcessCompleted_WithTimeAndProcessStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {0} {1}.
        /// </summary>
        internal static string ConsoleApplicationRunner_Output_RunningExe_WithPathAndArguments {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_Output_RunningExe_WithPathAndArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output: {0}.
        /// </summary>
        internal static string ConsoleApplicationRunner_OutputWhileRunning_WithOutput {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_OutputWhileRunning_WithOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit time: {0}.
        /// </summary>
        internal static string ConsoleApplicationRunner_ProcessStats_ForEndTime {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_ProcessStats_ForEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process statistics for {0}.
        /// </summary>
        internal static string ConsoleApplicationRunner_ProcessStats_ForFilePath {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_ProcessStats_ForFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-paged system memory (Kb): {0}.
        /// </summary>
        internal static string ConsoleApplicationRunner_ProcessStats_ForNonPagedSystemMemory {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_ProcessStats_ForNonPagedSystemMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paged memory (Kb): {0}.
        /// </summary>
        internal static string ConsoleApplicationRunner_ProcessStats_ForPagedMemory {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_ProcessStats_ForPagedMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paged system memory (Kb): {0}.
        /// </summary>
        internal static string ConsoleApplicationRunner_ProcessStats_ForPagedSystemMemory {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_ProcessStats_ForPagedSystemMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak paged memory (Kb): {0}.
        /// </summary>
        internal static string ConsoleApplicationRunner_ProcessStats_ForPeakPagedMemory {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_ProcessStats_ForPeakPagedMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak virtual memory (Kb): {0}.
        /// </summary>
        internal static string ConsoleApplicationRunner_ProcessStats_ForPeakVirtualMemory {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_ProcessStats_ForPeakVirtualMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak working set memory (Kb): {0}.
        /// </summary>
        internal static string ConsoleApplicationRunner_ProcessStats_ForPeakWorkingSetMemory {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_ProcessStats_ForPeakWorkingSetMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private memory (Kb): {0}.
        /// </summary>
        internal static string ConsoleApplicationRunner_ProcessStats_ForPrivateMemory {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_ProcessStats_ForPrivateMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privileged CPU time: {0}.
        /// </summary>
        internal static string ConsoleApplicationRunner_ProcessStats_ForPrivilegedCpuTime {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_ProcessStats_ForPrivilegedCpuTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time: {0}.
        /// </summary>
        internal static string ConsoleApplicationRunner_ProcessStats_ForStartTime {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_ProcessStats_ForStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total CPU time: {0}.
        /// </summary>
        internal static string ConsoleApplicationRunner_ProcessStats_ForTotalCpuTime {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_ProcessStats_ForTotalCpuTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time: {0}.
        /// </summary>
        internal static string ConsoleApplicationRunner_ProcessStats_ForTotalTime {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_ProcessStats_ForTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User CPU time: {0}.
        /// </summary>
        internal static string ConsoleApplicationRunner_ProcessStats_ForUserCpuTime {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_ProcessStats_ForUserCpuTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual memory (Kb): {0}.
        /// </summary>
        internal static string ConsoleApplicationRunner_ProcessStats_ForVirtualMemory {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_ProcessStats_ForVirtualMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working set memory (Kb): {0}.
        /// </summary>
        internal static string ConsoleApplicationRunner_ProcessStats_ForWorkingSetMemory {
            get {
                return ResourceManager.GetString("ConsoleApplicationRunner_ProcessStats_ForWorkingSetMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment [{0}].
        /// </summary>
        internal static string EnvironmentId_ToString {
            get {
                return ResourceManager.GetString("EnvironmentId_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument was out of range. The value was: {0}.
        /// </summary>
        internal static string Exceptions_Messages_ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file cannot be added to the same package multiple times..
        /// </summary>
        internal static string Exceptions_Messages_CannotAddDuplicateFileToPackage {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotAddDuplicateFileToPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to add a package multiple times..
        /// </summary>
        internal static string Exceptions_Messages_CannotAddDuplicatePackage {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotAddDuplicatePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to add a message to a test section if the section has already been finalized..
        /// </summary>
        internal static string Exceptions_Messages_CannotAddMessageToFinalizedTestSection {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotAddMessageToFinalizedTestSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to add a message to a test section if the section has not been initialized..
        /// </summary>
        internal static string Exceptions_Messages_CannotAddMessageToUninitializedTestSection {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotAddMessageToUninitializedTestSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to add new test sections to a report that has already been finalized..
        /// </summary>
        internal static string Exceptions_Messages_CannotAddSectionToFinalizedReport {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotAddSectionToFinalizedReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a new section to a report if the report data has not been initialized..
        /// </summary>
        internal static string Exceptions_Messages_CannotAddSectionToUninitializedReport {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotAddSectionToUninitializedReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to create a report if the report data has not been initialized..
        /// </summary>
        internal static string Exceptions_Messages_CannotBuildAnUninitializedReport {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotBuildAnUninitializedReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to create a test section if the section has not been initialized..
        /// </summary>
        internal static string Exceptions_Messages_CannotBuildAnUninitializedTestSection {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotBuildAnUninitializedTestSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to build a report if it has not been finalized..
        /// </summary>
        internal static string Exceptions_Messages_CannotBuildNonFinalizedReport {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotBuildNonFinalizedReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to create a test section if the section has not been finalized..
        /// </summary>
        internal static string Exceptions_Messages_CannotBuildNonFinalizedTestSection {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotBuildNonFinalizedTestSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to finalize a test section if the section has not be initialized..
        /// </summary>
        internal static string Exceptions_Messages_CannotFinalizeAnUninitializedTestSection {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotFinalizeAnUninitializedTestSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to finalize a report if the report data has not been initialized..
        /// </summary>
        internal static string Exceptions_Messages_CannotFinalizedAnUninitializedReport {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotFinalizedAnUninitializedReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to finalize a report more than once..
        /// </summary>
        internal static string Exceptions_Messages_CannotRefinalizeReport {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CannotRefinalizeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given object ({0}) is not of the same type as the object ({1}) to compare to..
        /// </summary>
        internal static string Exceptions_Messages_CompareArgument {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CompareArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given environment could not be loaded..
        /// </summary>
        internal static string Exceptions_Messages_CouldNotLoadEnvironment {
            get {
                return ResourceManager.GetString("Exceptions_Messages_CouldNotLoadEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given environment is already in use..
        /// </summary>
        internal static string Exceptions_Messages_EnvironmentAlreadyInUse {
            get {
                return ResourceManager.GetString("Exceptions_Messages_EnvironmentAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The environment could not be restored to its original state..
        /// </summary>
        internal static string Exceptions_Messages_FailedToRestoreEnvironment {
            get {
                return ResourceManager.GetString("Exceptions_Messages_FailedToRestoreEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given environment specification was invalid..
        /// </summary>
        internal static string Exceptions_Messages_InvalidEnvironmentSpecification {
            get {
                return ResourceManager.GetString("Exceptions_Messages_InvalidEnvironmentSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given machine could not be reached. It may be offline or not attached to the network..
        /// </summary>
        internal static string Exceptions_Messages_MachineUnreachable {
            get {
                return ResourceManager.GetString("Exceptions_Messages_MachineUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration value missing..
        /// </summary>
        internal static string Exceptions_Messages_MissingConfiguration {
            get {
                return ResourceManager.GetString("Exceptions_Messages_MissingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot pack or unpack a package without a file path..
        /// </summary>
        internal static string Exceptions_Messages_NeedPackagePath {
            get {
                return ResourceManager.GetString("Exceptions_Messages_NeedPackagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested package could not be found..
        /// </summary>
        internal static string Exceptions_Messages_PackageNotFound {
            get {
                return ResourceManager.GetString("Exceptions_Messages_PackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test execution has failed..
        /// </summary>
        internal static string Exceptions_Messages_TestExecutionFailure {
            get {
                return ResourceManager.GetString("Exceptions_Messages_TestExecutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown constraint.
        /// </summary>
        internal static string Exceptions_Messages_UnknownConstraint {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test [{0}].
        /// </summary>
        internal static string TestId_ToString {
            get {
                return ResourceManager.GetString("TestId_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test [{0}] for {1} ({2}) started by {3}.
        /// </summary>
        internal static string TestSpecification_ToString {
            get {
                return ResourceManager.GetString("TestSpecification_ToString", resourceCulture);
            }
        }
    }
}
