//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sherlock.Service.Executor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sherlock.Service.Executor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created storage directory for test at: {0}.
        /// </summary>
        internal static string Log_Messages_CreatedStorageDirectory_WithDirectory {
            get {
                return ResourceManager.GetString("Log_Messages_CreatedStorageDirectory_WithDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded test file to: {0}.
        /// </summary>
        internal static string Log_Messages_DownloadedTestData_WithFile {
            get {
                return ResourceManager.GetString("Log_Messages_DownloadedTestData_WithFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the test execution application.
        /// </summary>
        internal static string Log_Messages_FailedToConnectToTestApplication_WithError {
            get {
                return ResourceManager.GetString("Log_Messages_FailedToConnectToTestApplication_WithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create storage directory. Error was: {0}.
        /// </summary>
        internal static string Log_Messages_FailedToCreateDirectory_WithError {
            get {
                return ResourceManager.GetString("Log_Messages_FailedToCreateDirectory_WithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start test application. Error was: {0}.
        /// </summary>
        internal static string Log_Messages_FailedToStartTestApplication_WithError {
            get {
                return ResourceManager.GetString("Log_Messages_FailedToStartTestApplication_WithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started test application.
        /// </summary>
        internal static string Log_Messages_StartedTestApplication {
            get {
                return ResourceManager.GetString("Log_Messages_StartedTestApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfering test step report files for test step: {0}..
        /// </summary>
        internal static string Log_Messages_TransferingTestStepReportFiles_WithTestStep {
            get {
                return ResourceManager.GetString("Log_Messages_TransferingTestStepReportFiles_WithTestStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfering test step report files failed. Error was: {0}..
        /// </summary>
        internal static string Log_Messages_TransferingTestStepReportFilesFailed_WithException {
            get {
                return ResourceManager.GetString("Log_Messages_TransferingTestStepReportFilesFailed_WithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the test application..
        /// </summary>
        internal static string ReportSection_Error_FailedToConnectToTestingApplication {
            get {
                return ResourceManager.GetString("ReportSection_Error_FailedToConnectToTestingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create storage directory..
        /// </summary>
        internal static string ReportSection_Error_FailedToCreateStorageDirectory {
            get {
                return ResourceManager.GetString("ReportSection_Error_FailedToCreateStorageDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download test data..
        /// </summary>
        internal static string ReportSection_Error_FailedToDownloadTestData {
            get {
                return ResourceManager.GetString("ReportSection_Error_FailedToDownloadTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start the testing application..
        /// </summary>
        internal static string ReportSection_Error_FailedToStartTestingApplication {
            get {
                return ResourceManager.GetString("ReportSection_Error_FailedToStartTestingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization.
        /// </summary>
        internal static string ReportSection_Group_Name_Initialization {
            get {
                return ResourceManager.GetString("ReportSection_Group_Name_Initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded test data..
        /// </summary>
        internal static string ReportSection_Info_DownloadedTestData {
            get {
                return ResourceManager.GetString("ReportSection_Info_DownloadedTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started test application with endpoint ID: {0}.
        /// </summary>
        internal static string ReportSection_Info_StartedTestApplication_WithId {
            get {
                return ResourceManager.GetString("ReportSection_Info_StartedTestApplication_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing remote test application.
        /// </summary>
        internal static string ReportSection_Name_Initialization {
            get {
                return ResourceManager.GetString("ReportSection_Name_Initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes incoming requests for test execution and executes them..
        /// </summary>
        internal static string Service_Description {
            get {
                return ResourceManager.GetString("Service_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sherlock.Executor.
        /// </summary>
        internal static string Service_DisplayName {
            get {
                return ResourceManager.GetString("Service_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sherlock.ExecutorService.
        /// </summary>
        internal static string Service_ServiceName {
            get {
                return ResourceManager.GetString("Service_ServiceName", resourceCulture);
            }
        }
    }
}
