//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sherlock.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sherlock.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints out the command line options..
        /// </summary>
        internal static string CommandLine_Options_Help_Description {
            get {
                return ResourceManager.GetString("CommandLine_Options_Help_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?|h|help.
        /// </summary>
        internal static string CommandLine_Options_Help_Key {
            get {
                return ResourceManager.GetString("CommandLine_Options_Help_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full path to the configuration file that contains the information describing the test..
        /// </summary>
        internal static string CommandLine_Param_ConfigurationFile_Description {
            get {
                return ResourceManager.GetString("CommandLine_Param_ConfigurationFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c=|ConfigurationFile=.
        /// </summary>
        internal static string CommandLine_Param_ConfigurationFile_Key {
            get {
                return ResourceManager.GetString("CommandLine_Param_ConfigurationFile_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file defines an invalid value for the step order of a test step..
        /// </summary>
        internal static string Exceptions_Messages_ConfigurationInvalidStepOrder {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ConfigurationInvalidStepOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description element is missing from the configuration file..
        /// </summary>
        internal static string Exceptions_Messages_ConfigurationMissingDescriptionElement {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ConfigurationMissingDescriptionElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file is missing a parameters element for a test step..
        /// </summary>
        internal static string Exceptions_Messages_ConfigurationMissingParametersElement {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ConfigurationMissingParametersElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product name element is missing from the configuration file..
        /// </summary>
        internal static string Exceptions_Messages_ConfigurationMissingProductNameElement {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ConfigurationMissingProductNameElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product version element is missing from the configuration file..
        /// </summary>
        internal static string Exceptions_Messages_ConfigurationMissingProductVersionElement {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ConfigurationMissingProductVersionElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test purpose element is missing from the configuration file..
        /// </summary>
        internal static string Exceptions_Messages_ConfigurationMissingTestPurposeElement {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ConfigurationMissingTestPurposeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file does not define any environment constraints..
        /// </summary>
        internal static string Exceptions_Messages_ConfigurationNotDefiningAnyEnvironmentConstraints {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ConfigurationNotDefiningAnyEnvironmentConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file does not define any test steps..
        /// </summary>
        internal static string Exceptions_Messages_ConfigurationNotDefiningAnyTestSteps {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ConfigurationNotDefiningAnyTestSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test step parameter values in the configuration file must be defined as XDATA elements..
        /// </summary>
        internal static string Exceptions_Messages_ConfigurationTestStepParametersMustBeXData {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ConfigurationTestStepParametersMustBeXData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration file..
        /// </summary>
        internal static string Exceptions_Messages_InvalidConfigurationFile {
            get {
                return ResourceManager.GetString("Exceptions_Messages_InvalidConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input element was not valid for the current process..
        /// </summary>
        internal static string Exceptions_Messages_InvalidInputElement {
            get {
                return ResourceManager.GetString("Exceptions_Messages_InvalidInputElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid server response..
        /// </summary>
        internal static string Exceptions_Messages_InvalidServerResponse {
            get {
                return ResourceManager.GetString("Exceptions_Messages_InvalidServerResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration for the notification is missing..
        /// </summary>
        internal static string Exceptions_Messages_MissingNotificationConfiguration {
            get {
                return ResourceManager.GetString("Exceptions_Messages_MissingNotificationConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version number of the configuration does not match the version of the configuration reader..
        /// </summary>
        internal static string Exceptions_Messages_NonMatchingVersionFound {
            get {
                return ResourceManager.GetString("Exceptions_Messages_NonMatchingVersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version number of the configuration (version: {0}) does not match the version of the configuration reader (version: {1})..
        /// </summary>
        internal static string Exceptions_Messages_NonMatchingVersionFound_WithVersions {
            get {
                return ResourceManager.GetString("Exceptions_Messages_NonMatchingVersionFound_WithVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No builder was found for the given constraint configuration..
        /// </summary>
        internal static string Exceptions_Messages_UnknownConstraintConfiguration {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownConstraintConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No builder was found for the given notification configuration..
        /// </summary>
        internal static string Exceptions_Messages_UnknownNotificationConfiguration {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownNotificationConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No builder was found for the given test step configuration..
        /// </summary>
        internal static string Exceptions_Messages_UnknownTestStepConfiguration {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnknownTestStepConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sherlock ({0}).
        /// </summary>
        internal static string Header_ApplicationAndVersion {
            get {
                return ResourceManager.GetString("Header_ApplicationAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         {0} (version: {1}). For more information see: {2}.
        /// </summary>
        internal static string Header_OtherPackages_IdAndLicense {
            get {
                return ResourceManager.GetString("Header_OtherPackages_IdAndLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application makes use of the following open source software:.
        /// </summary>
        internal static string Header_OtherPackages_Intro {
            get {
                return ResourceManager.GetString("Header_OtherPackages_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: apollo.UI.console.exe [OPTIONS].
        /// </summary>
        internal static string Help_Usage_Intro {
            get {
                return ResourceManager.GetString("Help_Usage_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided configuration file does not exist. File should be at: {0}.
        /// </summary>
        internal static string Log_Error_ConfigurationFileDoesNotExist {
            get {
                return ResourceManager.GetString("Log_Error_ConfigurationFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file has unknown version [{0}]..
        /// </summary>
        internal static string Log_Error_ConfigurationFileVersionUnknown_WithVersion {
            get {
                return ResourceManager.GetString("Log_Error_ConfigurationFileVersionUnknown_WithVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the test server..
        /// </summary>
        internal static string Log_Error_CouldNotFindServer {
            get {
                return ResourceManager.GetString("Log_Error_CouldNotFindServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the local storage directory at {0}. Error was {1}..
        /// </summary>
        internal static string Log_Error_FailedToCreateStorageDirectory_WithDirectoryAndError {
            get {
                return ResourceManager.GetString("Log_Error_FailedToCreateStorageDirectory_WithDirectoryAndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read the configuration file. Error was {0}..
        /// </summary>
        internal static string Log_Error_FailedToReadConfigurationFile_WithError {
            get {
                return ResourceManager.GetString("Log_Error_FailedToReadConfigurationFile_WithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse the input parameters. Exception was: {0}.
        /// </summary>
        internal static string Log_Error_InvalidInputParameters_WithException {
            get {
                return ResourceManager.GetString("Log_Error_InvalidInputParameters_WithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to mark test as ready for processing. Server error code: {0}. Server reason: {1}..
        /// </summary>
        internal static string Log_Error_MarkingTestAsReadyFailed_WithStatusCodeAndReason {
            get {
                return ResourceManager.GetString("Log_Error_MarkingTestAsReadyFailed_WithStatusCodeAndReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} application configuration was missing from the application configuration file..
        /// </summary>
        internal static string Log_Error_MissingApplicationConfigurationValue {
            get {
                return ResourceManager.GetString("Log_Error_MissingApplicationConfigurationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing the test configuration. The exception is: {0}.
        /// </summary>
        internal static string Log_Error_ProcessingError_WithException {
            get {
                return ResourceManager.GetString("Log_Error_ProcessingError_WithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register the test environments. Server error code: {0}. Server reason: {1}.
        /// </summary>
        internal static string Log_Error_TestEnvironmentRegistrationFailed_WithStatusCodeAndReason {
            get {
                return ResourceManager.GetString("Log_Error_TestEnvironmentRegistrationFailed_WithStatusCodeAndReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload test files. Server error code: {0}. Server reason: {1}.
        /// </summary>
        internal static string Log_Error_TestFileUploadFailed_WithStatusCodeAndReason {
            get {
                return ResourceManager.GetString("Log_Error_TestFileUploadFailed_WithStatusCodeAndReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register test. Server error code: {0}. Server reason: {1}.
        /// </summary>
        internal static string Log_Error_TestRegistrationFailed_WithStatusCodeAndReason {
            get {
                return ResourceManager.GetString("Log_Error_TestRegistrationFailed_WithStatusCodeAndReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register the test parameters. Server error code: {0}. Server reason: {1}.
        /// </summary>
        internal static string Log_Error_TestStepParameterRegistrationFailed_WithStatusCodeAndReason {
            get {
                return ResourceManager.GetString("Log_Error_TestStepParameterRegistrationFailed_WithStatusCodeAndReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register the test steps. Server error code: {0}. Server reason: {1}.
        /// </summary>
        internal static string Log_Error_TestStepRegistrationFailed_WithStatusCodeAndReason {
            get {
                return ResourceManager.GetString("Log_Error_TestStepRegistrationFailed_WithStatusCodeAndReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sherlock.Console - Version: {0}.
        /// </summary>
        internal static string Log_Information_ApplicationAndVersion {
            get {
                return ResourceManager.GetString("Log_Information_ApplicationAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found one or more suitable Sherlock servers. Using first available one with endpoint ID: {0}.
        /// </summary>
        internal static string Log_Information_FoundSuitableServer_WithEndpoint {
            get {
                return ResourceManager.GetString("Log_Information_FoundSuitableServer_WithEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file path: {0}.
        /// </summary>
        internal static string Log_Information_InputParameterConfigurationFile {
            get {
                return ResourceManager.GetString("Log_Information_InputParameterConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading configuration file from: {0}..
        /// </summary>
        internal static string Log_Information_ReadingConfigurationFile_WithFile {
            get {
                return ResourceManager.GetString("Log_Information_ReadingConfigurationFile_WithFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test was queued. The test ID is: {0}.
        /// </summary>
        internal static string Log_Information_TestQueued {
            get {
                return ResourceManager.GetString("Log_Information_TestQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking test as ready..
        /// </summary>
        internal static string Log_Trace_MarkingTestAsReady {
            get {
                return ResourceManager.GetString("Log_Trace_MarkingTestAsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering test..
        /// </summary>
        internal static string Log_Trace_RegisteringTest {
            get {
                return ResourceManager.GetString("Log_Trace_RegisteringTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering test environment [{0}] with operating system {1}..
        /// </summary>
        internal static string Log_Trace_RegisteringTestEnvironment_WithEnvironment {
            get {
                return ResourceManager.GetString("Log_Trace_RegisteringTestEnvironment_WithEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering test environments..
        /// </summary>
        internal static string Log_Trace_RegisteringTestEnvironments {
            get {
                return ResourceManager.GetString("Log_Trace_RegisteringTestEnvironments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering test step {0} of Type [{1}].
        /// </summary>
        internal static string Log_Trace_RegisteringTestStep_WithTestStep {
            get {
                return ResourceManager.GetString("Log_Trace_RegisteringTestStep_WithTestStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering test step. Key = {0}. Value = {1}..
        /// </summary>
        internal static string Log_Trace_RegisteringTestStepParameter_WithParameter {
            get {
                return ResourceManager.GetString("Log_Trace_RegisteringTestStepParameter_WithParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering test step parameters..
        /// </summary>
        internal static string Log_Trace_RegisteringTestStepParameters {
            get {
                return ResourceManager.GetString("Log_Trace_RegisteringTestStepParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering test steps..
        /// </summary>
        internal static string Log_Trace_RegisteringTestSteps {
            get {
                return ResourceManager.GetString("Log_Trace_RegisteringTestSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test environment registration complete..
        /// </summary>
        internal static string Log_Trace_TestEnvironmentsRegistrationComplete {
            get {
                return ResourceManager.GetString("Log_Trace_TestEnvironmentsRegistrationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test files upload completed..
        /// </summary>
        internal static string Log_Trace_TestFilesUploadCompleted {
            get {
                return ResourceManager.GetString("Log_Trace_TestFilesUploadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test marked as ready..
        /// </summary>
        internal static string Log_Trace_TestMarkedAsReady {
            get {
                return ResourceManager.GetString("Log_Trace_TestMarkedAsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test registration for test {0} complete..
        /// </summary>
        internal static string Log_Trace_TestRegistrationComplete_WithTestId {
            get {
                return ResourceManager.GetString("Log_Trace_TestRegistrationComplete_WithTestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test step parameter registration completed..
        /// </summary>
        internal static string Log_Trace_TestStepParametersRegistrationCompleted {
            get {
                return ResourceManager.GetString("Log_Trace_TestStepParametersRegistrationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test step registration complete..
        /// </summary>
        internal static string Log_Trace_TestStepRegistrationComplete {
            get {
                return ResourceManager.GetString("Log_Trace_TestStepRegistrationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading test file: {0}..
        /// </summary>
        internal static string Log_Trace_UploadingTestFile_WithFile {
            get {
                return ResourceManager.GetString("Log_Trace_UploadingTestFile_WithFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading test files..
        /// </summary>
        internal static string Log_Trace_UploadingTestFiles {
            get {
                return ResourceManager.GetString("Log_Trace_UploadingTestFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Sherlock server was found that could handle test requests..
        /// </summary>
        internal static string Log_Warning_NoSuitableServerFound {
            get {
                return ResourceManager.GetString("Log_Warning_NoSuitableServerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided configuration file does not exist..
        /// </summary>
        internal static string Output_Error_ConfigurationFileDoesNotExist {
            get {
                return ResourceManager.GetString("Output_Error_ConfigurationFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the test server..
        /// </summary>
        internal static string Output_Error_CouldNotFindServer {
            get {
                return ResourceManager.GetString("Output_Error_CouldNotFindServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided input parameters were not valid..
        /// </summary>
        internal static string Output_Error_InvalidInput {
            get {
                return ResourceManager.GetString("Output_Error_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to mark test ready for processing..
        /// </summary>
        internal static string Output_Error_MarkingTestAsReadyFailed {
            get {
                return ResourceManager.GetString("Output_Error_MarkingTestAsReadyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full path to a configuration file has to be provided..
        /// </summary>
        internal static string Output_Error_MissingValues {
            get {
                return ResourceManager.GetString("Output_Error_MissingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL of the Sherlock webservice was not provided in the application configuration file. Please update the configuration file..
        /// </summary>
        internal static string Output_Error_MissingWebServiceUrlConfiguration {
            get {
                return ResourceManager.GetString("Output_Error_MissingWebServiceUrlConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register test environments. Please see log for more detailed information..
        /// </summary>
        internal static string Output_Error_TestEnvironmentRegistrationFailed {
            get {
                return ResourceManager.GetString("Output_Error_TestEnvironmentRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload of test files failed. Please see the log for more detailed information..
        /// </summary>
        internal static string Output_Error_TestFileUploadFailed {
            get {
                return ResourceManager.GetString("Output_Error_TestFileUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register the test. Please see log for more detailed information..
        /// </summary>
        internal static string Output_Error_TestRegistrationFailed {
            get {
                return ResourceManager.GetString("Output_Error_TestRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register test parameters. Please see the log for more detailed information..
        /// </summary>
        internal static string Output_Error_TestStepParameterRegistrationFailed {
            get {
                return ResourceManager.GetString("Output_Error_TestStepParameterRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register test steps. Please see log for more detailed information..
        /// </summary>
        internal static string Output_Error_TestStepRegistrationFailed {
            get {
                return ResourceManager.GetString("Output_Error_TestStepRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing the test configuration..
        /// </summary>
        internal static string Output_Error_WhileProcessing {
            get {
                return ResourceManager.GetString("Output_Error_WhileProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking test ready for processing ....
        /// </summary>
        internal static string Output_Information_MarkingTestAsReady {
            get {
                return ResourceManager.GetString("Output_Information_MarkingTestAsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queueing test with server ....
        /// </summary>
        internal static string Output_Information_QueueingTest {
            get {
                return ResourceManager.GetString("Output_Information_QueueingTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading configuration file ....
        /// </summary>
        internal static string Output_Information_ReadingConfigurationFile {
            get {
                return ResourceManager.GetString("Output_Information_ReadingConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering test ....
        /// </summary>
        internal static string Output_Information_RegisteringTest {
            get {
                return ResourceManager.GetString("Output_Information_RegisteringTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering test environments ....
        /// </summary>
        internal static string Output_Information_RegisteringTestEnvironments {
            get {
                return ResourceManager.GetString("Output_Information_RegisteringTestEnvironments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering test parameters ....
        /// </summary>
        internal static string Output_Information_RegisteringTestStepParameters {
            get {
                return ResourceManager.GetString("Output_Information_RegisteringTestStepParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering test steps ....
        /// </summary>
        internal static string Output_Information_RegisteringTestSteps {
            get {
                return ResourceManager.GetString("Output_Information_RegisteringTestSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test was successfully send to the server. The test ID is: {0}.
        /// </summary>
        internal static string Output_Information_TestQueued_WithId {
            get {
                return ResourceManager.GetString("Output_Information_TestQueued_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading test files to the server ....
        /// </summary>
        internal static string Output_Information_UploadingTestFiles {
            get {
                return ResourceManager.GetString("Output_Information_UploadingTestFiles", resourceCulture);
            }
        }
    }
}
