//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sherlock.Service.Master.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sherlock.Service.Master.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An environment with the given ID has already been registered..
        /// </summary>
        internal static string Exceptions_Messages_AnEnvironmentWithTheGivenIDHasAlreadyBeenRegistered {
            get {
                return ResourceManager.GetString("Exceptions_Messages_AnEnvironmentWithTheGivenIDHasAlreadyBeenRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An environment with the given ID has not been registered..
        /// </summary>
        internal static string Exceptions_Messages_AnEnvironmentWithTheGivenIDHasNotBeenRegistered {
            get {
                return ResourceManager.GetString("Exceptions_Messages_AnEnvironmentWithTheGivenIDHasNotBeenRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A test with the given ID has already been registered..
        /// </summary>
        internal static string Exceptions_Messages_ATestWithTheGivenIDHasAlreadyBeenRegistered {
            get {
                return ResourceManager.GetString("Exceptions_Messages_ATestWithTheGivenIDHasAlreadyBeenRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring snapshot failed because the snapshot could not be found..
        /// </summary>
        internal static string Exceptions_Messages_HypervVirtualMachine_CouldNotGetSnapshot {
            get {
                return ResourceManager.GetString("Exceptions_Messages_HypervVirtualMachine_CouldNotGetSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start the Hyper-V virtual machine. The error code was: {0}..
        /// </summary>
        internal static string Exceptions_Messages_HypervVirtualMachine_FailedToStartMachine_WithErrorCode {
            get {
                return ResourceManager.GetString("Exceptions_Messages_HypervVirtualMachine_FailedToStartMachine_WithErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to terminate the Hyper-V virtual machine. The error code was: {0}..
        /// </summary>
        internal static string Exceptions_Messages_HypervVirtualMachine_FailedToTerminateMachine_WithErrorCode {
            get {
                return ResourceManager.GetString("Exceptions_Messages_HypervVirtualMachine_FailedToTerminateMachine_WithErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring snapshot failed because WMI job failed to complete successfully..
        /// </summary>
        internal static string Exceptions_Messages_HypervVirtualMachine_JobFailedToComplete {
            get {
                return ResourceManager.GetString("Exceptions_Messages_HypervVirtualMachine_JobFailedToComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring snapshot failed with unknown return code: {0}..
        /// </summary>
        internal static string Exceptions_Messages_HypervVirtualMachine_UnknownReturnCode {
            get {
                return ResourceManager.GetString("Exceptions_Messages_HypervVirtualMachine_UnknownReturnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The machine ({0}) could not be reached. It may be offline or not attached to the network..
        /// </summary>
        internal static string Exceptions_Messages_MachineUnreachable_WithNetworkName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_MachineUnreachable_WithNetworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No activator has been registered for the selected environment type..
        /// </summary>
        internal static string Exceptions_Messages_NoActivatorHasBeenRegisteredForTheEnvironment {
            get {
                return ResourceManager.GetString("Exceptions_Messages_NoActivatorHasBeenRegisteredForTheEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No environments with the given ID have been registered..
        /// </summary>
        internal static string Exceptions_Messages_NoEnvironmentWithTheGivenIDHasBeenRegistered {
            get {
                return ResourceManager.GetString("Exceptions_Messages_NoEnvironmentWithTheGivenIDHasBeenRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No test with the given ID has been registered..
        /// </summary>
        internal static string Exceptions_Messages_NoTestWithTheGivenIDHasBeenRegistered {
            get {
                return ResourceManager.GetString("Exceptions_Messages_NoTestWithTheGivenIDHasBeenRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The execution of the test has failed..
        /// </summary>
        internal static string Exceptions_Messages_TestExecutionFailure {
            get {
                return ResourceManager.GetString("Exceptions_Messages_TestExecutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sherlock Master Service ({0}).
        /// </summary>
        internal static string Header_ApplicationAndVersion {
            get {
                return ResourceManager.GetString("Header_ApplicationAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         {0} (version: {1}). For more information see: {2}.
        /// </summary>
        internal static string Header_OtherPackages_IdAndLicense {
            get {
                return ResourceManager.GetString("Header_OtherPackages_IdAndLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application makes use of the following open source software:.
        /// </summary>
        internal static string Header_OtherPackages_Intro {
            get {
                return ResourceManager.GetString("Header_OtherPackages_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Activating environment {1}.
        /// </summary>
        internal static string Log_Messages_ActivatingEnvironment_WithTestAndEnvironment {
            get {
                return ResourceManager.GetString("Log_Messages_ActivatingEnvironment_WithTestAndEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed test with ID: {0}.
        /// </summary>
        internal static string Log_Messages_CompletedTest_WithId {
            get {
                return ResourceManager.GetString("Log_Messages_CompletedTest_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Executing on environment {1}.
        /// </summary>
        internal static string Log_Messages_ExecutingTestOnEnvironment_WithTestAndEnvironment {
            get {
                return ResourceManager.GetString("Log_Messages_ExecutingTestOnEnvironment_WithTestAndEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to contact environment [{0}]..
        /// </summary>
        internal static string Log_Messages_FailedToContactEnvironment {
            get {
                return ResourceManager.GetString("Log_Messages_FailedToContactEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to contact environment [{0}]. An exception was thrown: {1}.
        /// </summary>
        internal static string Log_Messages_FailedToContactEnvironment_WithException {
            get {
                return ResourceManager.GetString("Log_Messages_FailedToContactEnvironment_WithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the file for test: {0}. Error was: {1}.
        /// </summary>
        internal static string Log_Messages_FailedToDeleteTestFiles_WithFileAndError {
            get {
                return ResourceManager.GetString("Log_Messages_FailedToDeleteTestFiles_WithFileAndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to shut down the machine environment. Error was: {0}.
        /// </summary>
        internal static string Log_Messages_FailedToShutdownEnvironment_WithError {
            get {
                return ResourceManager.GetString("Log_Messages_FailedToShutdownEnvironment_WithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start environment(s) for test. Error was: {0}.
        /// </summary>
        internal static string Log_Messages_FailedToStartEnvironments_WithError {
            get {
                return ResourceManager.GetString("Log_Messages_FailedToStartEnvironments_WithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable environment is available for test: {0}.
        /// </summary>
        internal static string Log_Messages_NoEnvironmentForTestCase {
            get {
                return ResourceManager.GetString("Log_Messages_NoEnvironmentForTestCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Packaging test files for environment {1}.
        /// </summary>
        internal static string Log_Messages_PackagingTestFilesForEnvironment_WithTestAndEnvironment {
            get {
                return ResourceManager.GetString("Log_Messages_PackagingTestFilesForEnvironment_WithTestAndEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment [{0}]: State: {1}.
        /// </summary>
        internal static string Log_Messages_ProgressFromEnvironment {
            get {
                return ResourceManager.GetString("Log_Messages_ProgressFromEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving new test for {0}({1}). Owned by {2} on endpoint {3}.
        /// </summary>
        internal static string Log_Messages_ReceivingTest_WithNameVersionOwnerAndEndpoint {
            get {
                return ResourceManager.GetString("Log_Messages_ReceivingTest_WithNameVersionOwnerAndEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started test [{0}] in environments [{1}]..
        /// </summary>
        internal static string Log_Messages_StartedTestOnEnvironments {
            get {
                return ResourceManager.GetString("Log_Messages_StartedTestOnEnvironments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing test files to: {0}.
        /// </summary>
        internal static string Log_Messages_StoringTestFiles_WithDirectory {
            get {
                return ResourceManager.GetString("Log_Messages_StoringTestFiles_WithDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test activation failed with an exception. Error was: {0}..
        /// </summary>
        internal static string Log_Messages_TestActivationFailed_WithError {
            get {
                return ResourceManager.GetString("Log_Messages_TestActivationFailed_WithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test files transferred successfully.
        /// </summary>
        internal static string Log_Messages_TestFilesStored {
            get {
                return ResourceManager.GetString("Log_Messages_TestFilesStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test queued with id: {0}.
        /// </summary>
        internal static string Log_Messages_TestQueued_WithId {
            get {
                return ResourceManager.GetString("Log_Messages_TestQueued_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storing report file for test {0} step {1} in report directory..
        /// </summary>
        internal static string Log_Messages_TransferingTestStepReportFiles_WithTestAndTestStep {
            get {
                return ResourceManager.GetString("Log_Messages_TransferingTestStepReportFiles_WithTestAndTestStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storing test step report files for test {0} step {1} failed. Error was {2}..
        /// </summary>
        internal static string Log_Messages_TransferingTestStepReportFilesFailed_WithTestAndTestStepAndError {
            get {
                return ResourceManager.GetString("Log_Messages_TransferingTestStepReportFilesFailed_WithTestAndTestStepAndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start environment(s) for test..
        /// </summary>
        internal static string ReportSection_Error_FailedToStartEnvironments {
            get {
                return ResourceManager.GetString("ReportSection_Error_FailedToStartEnvironments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost contact with environmentId: {0}.
        /// </summary>
        internal static string ReportSection_Error_LostContactWithEnvironment_WithEnvironment {
            get {
                return ResourceManager.GetString("ReportSection_Error_LostContactWithEnvironment_WithEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environments.
        /// </summary>
        internal static string ReportSection_Group_Name_Environments {
            get {
                return ResourceManager.GetString("ReportSection_Group_Name_Environments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization.
        /// </summary>
        internal static string ReportSection_Group_Name_Initialization {
            get {
                return ResourceManager.GetString("ReportSection_Group_Name_Initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting environments.
        /// </summary>
        internal static string ReportSection_Name_Environments {
            get {
                return ResourceManager.GetString("ReportSection_Name_Environments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading environments.
        /// </summary>
        internal static string ReportSection_Name_LoadEnvironments {
            get {
                return ResourceManager.GetString("ReportSection_Name_LoadEnvironments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes incoming requests for test execution, sends the tests off to a remote test environment and returns the test results to the requestor..
        /// </summary>
        internal static string Service_Description {
            get {
                return ResourceManager.GetString("Service_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sherlock.Master.
        /// </summary>
        internal static string Service_DisplayName {
            get {
                return ResourceManager.GetString("Service_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sherlock.MasterService.
        /// </summary>
        internal static string Service_ServiceName {
            get {
                return ResourceManager.GetString("Service_ServiceName", resourceCulture);
            }
        }
    }
}
